# Generated by Django 3.2 on 2021-11-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0003_auto_20211127_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='billgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='splitter.billgroup'),
        ),
    ]
