# Generated by Django 3.2 on 2021-11-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0004_billgroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='billgroup',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
