# Generated by Django 3.2 on 2022-05-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitter', '0006_auto_20220514_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_lines',
            field=models.ManyToManyField(to='splitter.BillLines'),
        ),
    ]
